// packages/argon-router-vue/lib/link.tsx
import { useRouterContext } from './use-router';
import { useUnit } from 'effector-vue/composition';
import { computed, defineComponent, h } from 'vue';
import { LinkProps } from './types';

/**
 * @description Navigates user to provided route on click
 * @link https://movpushmov.dev/argon-router/react/link.html
 * @example ```tsx
 * import { Link } from '@argon-router/react';
 * import { routes } from '@shared/routing';
 *
 * function Profile({ user }) {
 *   return (
 *     <>
 *       <Link to={routes.settings}>Settings</Link>
 *
 *       {user.posts.map((post) => (
 *         <Link to={routes.editPost} params={{ id: post.id }}>
 *           Edit post
 *         </Link>
 *       ))}
 *     </>
 *   );
 * }
 * ```
 */
export const Link = defineComponent<LinkProps<any>>((props, { slots }) => {
  const routerContext = useRouterContext();
  const { mappedRoutes } = routerContext;

  const target = computed(() => {
    return mappedRoutes.find(({ route }) => route === props.to);
  });

  if (!target.value) {
    throw new Error(
      `[Link] Route with path "${props.to.path}" not found. Maybe it is not passed into createRouter?`,
    );
  }

  const { onOpen } = useUnit(props.to); // Замените на ваш хук/функцию

  const handleClick = (e: MouseEvent) => {
    props.onClick?.(e);

    if (e.defaultPrevented) return;
    if (props.target && props.target !== '_self') return;
    if (e.metaKey || e.altKey || e.ctrlKey || e.shiftKey) return;

    e.preventDefault();
    onOpen({ params: props.params || {} });
  };

  return () =>
    h(
      'a',
      {
        ...props,
        href: target.value?.build(props.params ?? undefined),
        onClick: handleClick,
      },
      slots.default?.(),
    );
});

// packages/argon-router-react/lib/link.tsx
import { RouteOpenedPayload } from '@argon-router/core';
import { ForwardedRef, forwardRef, ReactNode } from 'react';
import { useRouterContext } from './use-router';
import { useUnit } from 'effector-react';
import { LinkProps } from './types';

type ForwardedLink = <Params = void>(
  props: LinkProps<Params> & { ref?: ForwardedRef<HTMLAnchorElement> },
) => ReactNode;

/**
 * @description Navigates user to provided route on click
 * @link https://movpushmov.dev/argon-router/react/link.html
 * @example ```tsx
 * import { Link } from '@argon-router/react';
 * import { routes } from '@shared/routing';
 *
 * function Profile({ user }) {
 *   return (
 *     <>
 *       <Link to={routes.settings}>Settings</Link>
 *
 *       {user.posts.map((post) => (
 *         <Link to={routes.editPost} params={{ id: post.id }}>
 *           Edit post
 *         </Link>
 *       ))}
 *     </>
 *   );
 * }
 * ```
 */
export const Link: ForwardedLink = forwardRef<
  HTMLAnchorElement,
  LinkProps<any>
>((props, ref) => {
  const { to, params, onClick, ...anchorProps } = props;

  const { mappedRoutes } = useRouterContext();
  const target = mappedRoutes.find(({ route }) => route === to);

  const { onOpen } = useUnit(to);

  if (!target) {
    throw new Error(
      `[Link] Route with path "${to.path}" not found. Maybe it is not passed into createRouter?`,
    );
  }

  return (
    <a
      {...anchorProps}
      ref={ref}
      href={target.build(params ?? undefined)}
      onClick={(e) => {
        onClick?.(e);

        // allow user to prevent navigation
        if (e.defaultPrevented) {
          return;
        }

        // let browser handle "_blank" target and etc
        if (anchorProps.target && anchorProps.target !== '_self') {
          return;
        }

        // skip modified events (like cmd + click to open the link in new tab)
        if (e.metaKey || e.altKey || e.ctrlKey || e.shiftKey) {
          return;
        }

        e.preventDefault();

        onOpen({ params: params || {} } as RouteOpenedPayload<any>);
      }}
    />
  );
});
